spring:
  profiles:
    active: dev
springdoc:
  use-fqn: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource: # DB? ???? ?? DataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
  output:
    ansi:
      enabled: always # ???? ?? ??? ????

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # JPA? ???? ??? ??
        format_sql: false # ?? ?? ????? ??? (???, ? ?)
        use_sql_comments: false # ???? ??? ???
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000 # JPA?? ????? ??? default_batch_fetch_size ???? ?????? ?? ???? ???? IN?? ??? ??? ??

logging:
  level:
    org:
      hibernate:
        type: trace # ??? ????? ?? ?? ?? ????? ??

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

---
spring:
  config:
    activate:
      on-profile: dev
  datasource: # DB? ???? ?? DataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    url: ${AWS_DB_URL}
  output:
    ansi:
      enabled: always # ???? ?? ??? ????

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # JPA? ???? ??? ??
        format_sql: false # ?? ?? ????? ??? (???, ? ?)
        use_sql_comments: false # ???? ??? ???
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000 # JPA?? ????? ??? default_batch_fetch_size ???? ?????? ?? ???? ???? IN?? ??? ??? ??

logging:
  level:
    org:
      hibernate:
        type: trace # ??? ????? ?? ?? ?? ????? ??

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400

cool-sms:
  api-key: ${COOL_SMS_API_KEY}
  api-secret: ${COOL_SMS_API_SECRET}
  from-number: ${COOL_SMS_FROM_NUMBER}
  domain: ${COOL_SMS_DOMAIN}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource: # DB? ???? ?? DataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${aws.db.username}
    password: ${aws.db.password}
    url: ${aws.db.url}
  output:
    ansi:
      enabled: always # ???? ?? ??? ????

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # JPA? ???? ??? ??
        format_sql: false # ?? ?? ????? ??? (???, ? ?)
        use_sql_comments: false # ???? ??? ???
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000 # JPA?? ????? ??? default_batch_fetch_size ???? ?????? ?? ???? ???? IN?? ??? ??? ??

logging:
  level:
    org:
      hibernate:
        type: trace # ??? ????? ?? ?? ?? ????? ??

jwt:
  header: Authorization
  secret: ${jwt.secret}
  token-validity-in-seconds: 1800000 # ms

cool-sms:
  api-key: ${cool.sms.api.key}
  api-secret: ${cool.sms.api.secret}
  from-number: ${cool.sms.from.number}
  domain: ${cool.sms.domain}

